/**
 * Playlist-Beschreibungen mit Zeitstempel.
 *
 * Wird von Browser und Server genutzt, damit beide identisch formatieren.
 * Format bewusst fest (DD.MM.YYYY, HH:MM) statt gebietsabhängig – so bleibt
 * die Angabe in der Playlist eindeutig lesbar.
 */

export type Lang = 'de' | 'en';

function two(value: number): string {
  return String(value).padStart(2, '0');
}

export function formatStampDate(date = new Date()): string {
  return `${two(date.getDate())}.${two(date.getMonth() + 1)}.${date.getFullYear()}`;
}

export function formatStampDateTime(date = new Date()): string {
  return `${two(date.getHours())}:${two(date.getMinutes())} ${formatStampDate(date)}`;
}

/** Ein Codewort muss enthalten bleiben – daran wird die Playlist wiedererkannt */
const WEEKLY_BASE =
  'A weekly autogenerated Playlist by emphasize.me based on your hearing profile';
const SHARED_BASE = 'A shared playlist kept in sync by emphasize.me — emphasis shared playlist';

/*
 * Achtung beim Ändern: "emphasize.me" enthält NICHT die Zeichenfolge "emphasis"
 * (z statt s). Beide Wörter müssen geprüft werden – "emphasis" erkennt die
 * Beschreibungen, die vor der Umbenennung von emphasis.dev geschrieben wurden.
 * Ohne den Abwärtsfall würde die App bestehende Playlists nicht wiederfinden
 * und stattdessen doppelte anlegen.
 */
const CODEWORDS = ['emphasize.me', 'emphasis'];

/** Stammt diese Playlist von Emphasis? (aktuelle und alte Beschreibungen) */
export function isEmphasisDescription(description?: string): boolean {
  if (!description) return false;
  const text = description.toLowerCase();
  return CODEWORDS.some((word) => text.includes(word));
}

export function weeklyMixDescription(lang: Lang, date = new Date()): string {
  const label = lang === 'de' ? 'Zuletzt erstellt' : 'Last created';
  // Mit Uhrzeit: manuell lässt sich mehrmals am Tag generieren, ein reines
  // Datum würde zwei Läufe nicht unterscheidbar machen
  return `${WEEKLY_BASE} · ${label} ${formatStampDateTime(date)}`;
}

export function sharedPlaylistDescription(lang: Lang, date?: Date): string {
  if (!date) return SHARED_BASE;
  const label = lang === 'de' ? 'Zuletzt synchronisiert' : 'Last synced';
  return `${SHARED_BASE} · ${label} ${formatStampDateTime(date)}`;
}
