/**
 * Playlist-Beschreibungen mit Zeitstempel.
 *
 * Wird von Browser und Server genutzt, damit beide identisch formatieren.
 * Format bewusst fest (DD.MM.YYYY, HH:MM) statt gebietsabhängig – so bleibt
 * die Angabe in der Playlist eindeutig lesbar.
 */

export type Lang = 'de' | 'en';

function two(value: number): string {
  return String(value).padStart(2, '0');
}

export function formatStampDate(date = new Date()): string {
  return `${two(date.getDate())}.${two(date.getMonth() + 1)}.${date.getFullYear()}`;
}

export function formatStampDateTime(date = new Date()): string {
  return `${two(date.getHours())}:${two(date.getMinutes())} ${formatStampDate(date)}`;
}

/** Das Codewort "emphasis" muss enthalten bleiben – daran wird die Playlist wiedererkannt */
const WEEKLY_BASE =
  'A weekly autogenerated Playlist by emphasis.dev based on your hearing profile';
const SHARED_BASE = 'A shared playlist kept in sync by emphasis.dev — emphasis shared playlist';

export function weeklyMixDescription(lang: Lang, date = new Date()): string {
  const label = lang === 'de' ? 'Zuletzt erstellt' : 'Last created';
  return `${WEEKLY_BASE} · ${label} ${formatStampDate(date)}`;
}

export function sharedPlaylistDescription(lang: Lang, date?: Date): string {
  if (!date) return SHARED_BASE;
  const label = lang === 'de' ? 'Zuletzt synchronisiert' : 'Last synced';
  return `${SHARED_BASE} · ${label} ${formatStampDateTime(date)}`;
}
